### ISSUE TITLE
DryIoc.Microsoft.DependencyInjection Dependencies

### ISSUE THREAD

**Issue by Fruchuxs** [dadhi/DryIoc#113]
Hey, I'm working on a new asp.net core 2.1 app (I don't want to use 2.2 cuz of missing long term support) and I wanted to check out your nice work at DryIoc 4.0. But I can't use it, because DryIoc.Microsoft.DependencyInjection needs Microsoft.Extensions.DependencyInjection.Abstractions 2.2 which violates the project constraints.

> Microsoft.AspNetCore.App 2.1.1 requires Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.1.1 && < 2.2.0) but version Microsoft.Extensions.DependencyInjection.Abstractions 2.2.0 was resolved.

Another problem is, that it seems I can't use .net core 2.2.2x with Visual Studio 2017:
https://stackoverflow.com/questions/53329290/net-core-2-2-cant-be-selected-in-visual-studio-build-framework#answer-55529011

So I don't see any good way to use DryIoc 4.0 in asp.net core 2.1 currently. :(

**Comment by dadhi** [comment]
This is bad. I will try to release 2.1 compat version.

**Comment by Fruchuxs** [comment]
I tested it out out: VS 2019 supports the new .net core version. [But no LTS for 2.2](https://dotnet.microsoft.com/platform/support/policy/dotnet-core). It's kinda like a joke from microsoft.

**Comment by dadhi** [comment]
I am not aware about LTS support, but apperently they're not changing MS.Ext.DI 2.2 version in Asp .Net Core 3. That way DryIoc.MS.DI is kinda ready for v3 without changes.

**Comment by Fruchuxs** [comment]
I switched to VS19 and changed the project SDK to 2.2.2x for my new project.
But I'm not sure if commercial users of VS17 with business or enterprise license can also easily upgrade to VS19 to use DryIoc 4 in asp.net core projects. 
I also think that this is a problem for LTS awared users like me: I can't upgrade another project to DryIoc 4 and need to stick to a DryIoc 3 Preview because of performance issues - until core 3.0 LTS comes out.

**Comment by dadhi** [comment]
I have published DryIoc.Microsoft.DependencyInjection.3.0.2.nupkg with direct support for A.NC 2.1.1
Check in a minute.

**Comment by Fruchuxs** [comment]
Hey, thank you! Will check it out later.

**Comment by deathgore** [comment]
I have the same issue.
The DryIoc.Microsoft.DependencyInjection.3.0.2.nupkg  helps for .NETStandard projects.
But for .NETCoreApp the problem is still there.

**Comment by dadhi** [comment]
:( Something tells me that I need to release a specific version (different from the 3.0.2) targeting netcoreapp 2.1, or may be even create a separate package. 

But before that could you try to add explicit project reference to MS.DI?
```
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.1.1" />
```

**Comment by deathgore** [comment]
I have tried that before. It bubbles up to Microsoft.AspNetCore.Mvc.Core downgrade.

NU1605: Detected package downgrade: Microsoft.Extensions.DependencyInjection.Abstractions from 2.2.0 to 2.1.1. Reference the package directly from the project to select a different version. 
 .....Tests.netCore -> ......Web.AspNetCore.netCore -> Microsoft.AspNetCore.Mvc.Core 2.2.2 -> Microsoft.Extensions.DependencyInjection 2.2.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.2.0) 
 ......Tests.netCore -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.1.1)

**Comment by dadhi** [comment]
I have split package in two and published DryIoc.MS.DI v3.0.3 and DryIoc.MS.DI.AspNetCore2_1 v3.0.3

**Comment by deathgore** [comment]
Now nuget update succedded.
Thank you.
