### ISSUE TITLE
Possibility to prevent disposal in child container

### ISSUE THREAD

**Issue by lucas-rombaldi** [dadhi/DryIoc#259]
Hi,

I am upgrading our DryIoC package reference from version 2.12.1 to 4.1.4, but I'm having some trouble working with the child container.

**Situation:**
I am creating a child container based on a container with some services registered (including himself, as my own IoCContainer interface). The problem is that when I'm disposing the child container, all the services registered previously in the parent container are being disposed too. So my question is: is there a way to set the registrations copy to prevent disposal?
Somehow, it wasn't a problem when I used `WithImplicitRootOpenScope` in the container constructor.

I have tried to create the child container by two ways:
```
var childContainer = parentContainer.WithRegistrationsCopy();
```
And
```
var childContainer = Container.With(
   Container.Rules,
   Container.ScopeContext,
   RegistrySharing.CloneAndDropCache,
   Container.SingletonScope.Clone()
);
```

**Comment by dadhi** [comment]
Could you provide the more complete test with creating both parent and child, and the disposal?

**Comment by lucas-rombaldi** [comment]
Sure! Actually, this is a continuation of the issue https://github.com/dadhi/DryIoc/issues/136, posted by my colleague about a year ago. The thing is that I'm not sure about the correct behavior in this situation, because I have singletons registered in the parent container, and they're disposed together to the child container.

Following the same example of the other issue:

```
var container = new Container();
container.Register<MyService>(Reuse.Singleton);

var someService1 = container.Resolve<MyService>();

using (var childContainer = container.With(
                            container.Rules,
                            container.ScopeContext,
                            RegistrySharing.CloneAndDropCache,
                            container.SingletonScope.Clone()))
{
    var someService2 = childContainer.Resolve<MyService>();
}

var someService3 = container.Resolve<MyService>();
```

After the child container disposal, the `MyService` singleton is disposed too. I think that this may be a problem in some situations, because I think I still should be able to get the singleton instance through the parent container. This situation is a little problem for me also because I always register a container wrapper in itself, so that I can resolve it this way too. See the other example:

```
	public static void Main(string[] args)
	{
		var container = new MyContainer();
		container.Register<MyService>(Reuse.Singleton);

		var someService1 = container.Resolve<MyService>();

		using (var childContainer = container.CreateChildContainer())
		{
			var someService2 = childContainer.Resolve<MyService>();
		}

		var someService3 = container.Resolve<MyService>();
	}

	public class MyContainer : IDisposable
	{
		public MyContainer()
		{
			Container = new Container()
				.WithDependencyInjectionAdapter()
				.With(r => r.With(FactoryMethod.ConstructorWithResolvableArgumentsIncludingNonPublic));

			Container.RegisterInstance<MyContainer>(this, IfAlreadyRegistered.Replace);
		}

		public MyContainer(IContainer container)
		{
			Container = container;
			Container.RegisterInstance<MyContainer>(this, IfAlreadyRegistered.Replace);
		}

		public IContainer Container { get; set; }

		public MyContainer CreateChildContainer()
		{
			var childContainer = Container.With(
								Container.Rules,
								Container.ScopeContext,
								RegistrySharing.CloneAndDropCache,
								Container.SingletonScope.Clone());
			return new MyContainer(childContainer);
		}

		public void Dispose()
		{
			Container?.Dispose();
		}

		public void Register<T>(IReuse reuse)
		{
			Container.Register<T>(reuse);
		}

		public T Resolve<T>()
		{
			return Container.Resolve<T>();
		}
	}
```

The only way I found to not dispose the parent container in this situation is adding a `Setup.With(preventDisposal: true)` in its `RegisterInstance` and that works fine, but what about the other instances registered in the parent container, I'm not sure that they should be disposed together to the child container, so I was figuring that maybe there is an option so that the instances copied to the child container don't be disposed in it, but just when the parent container is disposed.

**Comment by dadhi** [comment]
Thank you, I will return to this when I have time.

**Comment by wjrogers** [comment]
Hi, I might be able to help because I struggled with the same problem.

If I remember right, the root cause is that disposing the container disposes its root (singleton) scope, so even if you've created a clone of the parent container's singleton scope, disposing it will still dispose all of the singleton services that had been resolved from the parent container.

The solution I struck on was to create an explicit "root" scope and use it as the child container:

```csharp
var child = parent.With();

// DryIoc.Microsoft.DependencyInjection.DryIocAdapter.WithDependencyInjectionAdapter()
// (this is where I create new registrations on the child container, using MS DI here)
child.Use<IServiceScopeFactory>(r => new DryIocServiceScopeFactory(r));
child.Populate(containerBuilder, RegisterDescriptor);

// Return a scope because it prevents DryIoc from disposing the singletons.
return child.OpenScope();
```

**Comment by dadhi** [comment]
@wjrogers , @lucas-rombaldi 

The problem here that we are dealing with the same instance of `MyService` (from the original example). Then "child" container should behave the following:

1. If the singleton is already resolved in the parent then it should not be disposed in child
2. If the singleton is not resolved in the parent - then it should be resolved in child, or not?

**Comment by lucas-rombaldi** [comment]
@wjrogers, thank you for your answer, I'll test it soon!

@dadhi 
Actually it's a really tricky situation. I'm still not convinced that the child container should dispose a singleton registered in the parent container at all, as if we could mark everything that has been copied to the child container as "not managed" or something. Anyway, this "resolve" control already would help a lot.
Just to be clear, what you're suggesting isn't possible to do with the current version yet, correct? Or is it possible to configure somehow?

**Comment by dadhi** [comment]
> if we could mark everything that has been copied to the child container as "not managed"

I don't see how you can do that now. 
I suggest to look into different direction to represent "child" container as a nested scope. Scopes form a hieararchy and in my oppinion much better handle the "parent" singletons (parent scope services).
There are technics to isolate the available service for diffetent scopes, like using named scopes and `Reuse.ScopedTo`

**Comment by dadhi** [comment]
I have returned back to this issue and this is how you can do that:

```cs
            var container = new Container();
            container.Register<MyService>(Reuse.Singleton);

            var service1 = container.Resolve<MyService>();
            MyService service2 = null;

            using (var childContainer = container.WithoutSingletonsAndCache().CreateChild())
            {
                service2 = childContainer.Resolve<MyService>(); // expecting it to be a new singleton, right?
            }

            Assert.IsTrue(service2.IsDisposed);
            Assert.IsFalse(service1.IsDisposed);

            var service3 = container.Resolve<MyService>();
            Assert.AreSame(service1, service3);

            container.Dispose();
            Assert.IsTrue(service1.IsDisposed);
```
